# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-06-11 00:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_in', models.IntegerField()),
                ('problem', models.IntegerField()),
                ('status', models.IntegerField(choices=[(1, 'Aceita'), (2, 'Resposta incorreta'), (3, 'Erro de compilação'), (4, 'Erro de execução'), (5, 'Erro de apresentação'), (6, 'Outro')])),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='website.Match')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='problem_categories',
            field=models.ManyToManyField(to='website.ProblemCategory'),
        ),
    ]
