# Generated by Django 2.1.2 on 2018-10-13 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20180610_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='first_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='website.Team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='matchscore',
            name='judge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='participant',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.Campus'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.Course'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='participant',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.Year'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
