# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20160716_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontuacao',
            name='tempo',
            field=models.IntegerField(default=0),
        ),
    ]
