# Generated by Django 2.1.2 on 2018-10-13 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20181013_1119'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProblemCategory',
            new_name='ProblemType',
        ),
    ]
