# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 12:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_pontuacao_tempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='inicio',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='termino',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
