# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 03:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20160720_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='jogo',
            name='participantes',
            field=models.ManyToManyField(related_name='jogos', to='website.Participante'),
        ),
        migrations.AlterField(
            model_name='pontuacao',
            name='participante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Participante'),
        ),
    ]
