# Generated by Django 2.1.2 on 2018-10-13 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20181013_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='problem_categories',
            new_name='problem_types',
        ),
    ]
