# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-04 12:24
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0006_auto_20160803_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('start', models.TimeField(default=django.utils.timezone.now)),
                ('end', models.TimeField(default=django.utils.timezone.now)),
                ('local', models.CharField(max_length=255)),
                ('intercampi', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MatchScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('time', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='website.Match')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=255)),
                ('course', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Category',
        ),
        migrations.RemoveField(
            model_name='competicao',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='competicao',
            name='responsavel',
        ),
        migrations.RemoveField(
            model_name='competicao',
            name='torneio',
        ),
        migrations.RemoveField(
            model_name='jogo',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='jogo',
            name='competicao',
        ),
        migrations.RemoveField(
            model_name='jogo',
            name='participantes',
        ),
        migrations.RemoveField(
            model_name='jogo',
            name='responsavel',
        ),
        migrations.RemoveField(
            model_name='pontuacao',
            name='jogo',
        ),
        migrations.RemoveField(
            model_name='pontuacao',
            name='participante',
        ),
        migrations.RemoveField(
            model_name='torneio',
            name='responsavel',
        ),
        migrations.RemoveField(
            model_name='torneio',
            name='sede',
        ),
        migrations.RenameField(
            model_name='campus',
            old_name='cidade',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='campus',
            old_name='numero',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='regras',
            new_name='rules',
        ),
        migrations.DeleteModel(
            name='Competicao',
        ),
        migrations.DeleteModel(
            name='Jogo',
        ),
        migrations.DeleteModel(
            name='Participante',
        ),
        migrations.DeleteModel(
            name='Pontuacao',
        ),
        migrations.DeleteModel(
            name='Torneio',
        ),
        migrations.AddField(
            model_name='tournament',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.Campus'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matchscore',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Participant'),
        ),
        migrations.AddField(
            model_name='match',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Campus'),
        ),
        migrations.AddField(
            model_name='match',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='website.Competition'),
        ),
        migrations.AddField(
            model_name='match',
            name='participants',
            field=models.ManyToManyField(related_name='participants', to='website.Participant'),
        ),
        migrations.AddField(
            model_name='match',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competition',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Category'),
        ),
        migrations.AddField(
            model_name='competition',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competition',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='website.Tournament'),
        ),
    ]
