# Generated by Django 2.1.2 on 2018-10-13 21:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20181013_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submitted_in',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 13, 18, 45, 49, 808168)),
            preserve_default=False,
        ),
    ]
