# Generated by Django 2.1.2 on 2018-10-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20181014_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='year',
            field=models.PositiveSmallIntegerField(default=2018),
            preserve_default=False,
        ),
    ]
