# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-06 04:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20170204_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchscore',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='website.Match'),
        ),
    ]
