# Generated by Django 2.1.2 on 2018-11-02 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_team_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchProblemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='match',
            name='problem_types',
        ),
        migrations.AddField(
            model_name='matchproblemtype',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Match'),
        ),
        migrations.AddField(
            model_name='matchproblemtype',
            name='problem_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.ProblemType'),
        ),
    ]
