# Generated by Django 2.1.2 on 2018-11-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20181102_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='problem_types',
            field=models.ManyToManyField(through='website.MatchProblemType', to='website.ProblemType'),
        ),
    ]
