# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-06 04:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20170206_0246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchscore',
            options={'permissions': (('teste', 'Pode adicionar placar'),)},
        ),
    ]
