# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-16 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.Group'),
        ),
    ]
