# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-06 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_matchscore_responsible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchscore',
            options={'permissions': (('add_result', 'Pode adicionar resultado'),)},
        ),
        migrations.RemoveField(
            model_name='matchscore',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='matchscore',
            name='score',
        ),
        migrations.RemoveField(
            model_name='matchscore',
            name='time',
        ),
        migrations.AddField(
            model_name='matchscore',
            name='first_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='website.Participant'),
        ),
        migrations.AddField(
            model_name='matchscore',
            name='second_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='website.Participant'),
        ),
        migrations.AddField(
            model_name='matchscore',
            name='third_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='website.Participant'),
        ),
    ]
