# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-09 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20170207_2135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchscore',
            options={},
        ),
        migrations.RemoveField(
            model_name='matchscore',
            name='first_place',
        ),
        migrations.RemoveField(
            model_name='matchscore',
            name='responsible',
        ),
        migrations.RemoveField(
            model_name='matchscore',
            name='second_place',
        ),
        migrations.RemoveField(
            model_name='matchscore',
            name='third_place',
        ),
        migrations.AddField(
            model_name='match',
            name='first_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_place', to='website.Participant'),
        ),
        migrations.AddField(
            model_name='match',
            name='second_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_place', to='website.Participant'),
        ),
        migrations.AddField(
            model_name='match',
            name='third_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_place', to='website.Participant'),
        ),
        migrations.AddField(
            model_name='matchscore',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Participant'),
        ),
        migrations.AddField(
            model_name='matchscore',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
