# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-09 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20170209_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='second_place',
        ),
        migrations.RemoveField(
            model_name='match',
            name='third_place',
        ),
        migrations.AlterField(
            model_name='match',
            name='first_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_place', to='website.Participant'),
        ),
    ]
