# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-09 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20170209_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchscore',
            name='time',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
