# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-10 00:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_matchscore_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'permissions': ('see_matchs_processing', 'Pode adicionar resultado')},
        ),
    ]
