# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-10 00:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20170209_2234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'permissions': ('see_matchs', 'Pode adicionar resultado')},
        ),
    ]
