# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-10 00:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_auto_20170209_2236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={},
        ),
    ]
