# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-10 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_auto_20170209_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
