# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-14 01:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_match_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='complete',
        ),
    ]
