# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-15 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_remove_match_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchscore',
            name='time',
            field=models.TimeField(blank=True),
        ),
    ]
