# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-15 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_auto_20170215_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='matchscore',
            name='participant',
        ),
        migrations.AddField(
            model_name='match',
            name='teams',
            field=models.ManyToManyField(related_name='teams', to='website.Team'),
        ),
        migrations.AddField(
            model_name='matchscore',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchs', to='website.Competition'),
        ),
        migrations.AlterField(
            model_name='match',
            name='first_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_place', to='website.Team'),
        ),
    ]
