# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-16 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_auto_20170216_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchscore',
            name='time',
            field=models.TimeField(default='00:00'),
        ),
    ]
