# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-16 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20170214_1630'),
        ('website', '0029_auto_20170216_0240'),
    ]

    operations = [
    ]
