# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-21 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_auto_20170216_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='need_score',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='need_time',
            field=models.BooleanField(default=False),
        ),
    ]
