# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-24 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_auto_20170223_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchscore',
            name='score',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='matchscore',
            name='time',
            field=models.TimeField(blank=True, default='00:00'),
        ),
    ]
