# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-20 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_merge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='leader',
            new_name='valid',
        ),
        migrations.AddField(
            model_name='participant',
            name='school',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
