# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-18 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_participant_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='school',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
