# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-24 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_auto_20170224_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchscore',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='matchscore',
            name='time',
            field=models.TimeField(blank=True, default='00:00:00', null=True),
        ),
    ]
