# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-20 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_auto_20170220_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='year',
            field=models.IntegerField(choices=[(1, '1º'), (2, '2º'), (3, '3º')], default=2012),
            preserve_default=False,
        ),
    ]
