# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-18 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_participant_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='school',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='participant',
            name='year',
            field=models.IntegerField(choices=[(1, '1º'), (2, '2º'), (3, '3º')]),
        ),
    ]
