# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-24 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_auto_20170224_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='location',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Campus'),
        ),
    ]
