# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-18 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_auto_20170218_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='leader',
            new_name='valid',
        ),
    ]
