# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-24 21:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_auto_20170224_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Category'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='website.Tournament'),
        ),
        migrations.AlterField(
            model_name='match',
            name='campus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Campus'),
        ),
        migrations.AlterField(
            model_name='match',
            name='competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matchs', to='website.Competition'),
        ),
        migrations.AlterField(
            model_name='match',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='teams',
            field=models.ManyToManyField(null=True, related_name='teams', to='website.Team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Category'),
        ),
        migrations.AlterField(
            model_name='team',
            name='participants',
            field=models.ManyToManyField(null=True, related_name='team_participants', to='website.Participant'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
