# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-18 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_auto_20170218_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='mix_team',
            field=models.BooleanField(default=False),
        ),
    ]
