# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-20 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_team_mix_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='group',
        ),
        migrations.AddField(
            model_name='group',
            name='teams',
            field=models.ManyToManyField(related_name='group_teams', to='website.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Group'),
        ),
    ]
