# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-24 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_auto_20170224_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='teams',
            field=models.ManyToManyField(related_name='teams', to='website.Team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='participants',
            field=models.ManyToManyField(related_name='team_participants', to='website.Participant'),
        ),
    ]
