# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-09 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20170216_2335'),
        ('website', '0038_auto_20170224_1802'),
    ]

    operations = [
    ]
