# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-12 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('depth', models.IntegerField(default=0)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Competition')),
            ],
        ),
        migrations.RemoveField(
            model_name='participant',
            name='leader',
        ),
        migrations.AddField(
            model_name='participant',
            name='school',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='year',
            field=models.IntegerField(choices=[(1, '1º'), (2, '2º'), (3, '3º')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='mix_team',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='participants',
            field=models.ManyToManyField(related_name='teams', to='website.Participant'),
        ),
        migrations.AddField(
            model_name='group',
            name='teams',
            field=models.ManyToManyField(related_name='groups', to='website.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Group'),
        ),
    ]
