# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-12 22:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_auto_20170312_1908'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='TeamGroup',
        ),
    ]
