# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-18 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0041_auto_20170312_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='email',
        ),
    ]
